import os
import json
from dotenv import load_dotenv
from groq import Groq


load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)


# ----------------------------------------
# Explain Analysis Result
# ----------------------------------------

def explain(intent, data, history=None, parameters=None):
    """
    Convert structured analytics into a
    professional business explanation.
    """

    if history is None:
        history = []

    if parameters is None:
        parameters = {}

    recent_history = history[-3:]

    prompt = f"""
You are a Senior Business Intelligence Consultant.

You explain business analytics generated by an AI-powered Business Intelligence Assistant.

--------------------------------------------------

Conversation History

{json.dumps(recent_history, indent=4)}

--------------------------------------------------

Current Intent

{intent}

--------------------------------------------------

Current Parameters

{json.dumps(parameters, indent=4)}

--------------------------------------------------

Analysis Result

{json.dumps(data, indent=4)}

--------------------------------------------------

Instructions

The analytics have already been computed.

Never:
- perform calculations
- change numbers
- estimate values
- invent facts
- invent percentages
- invent trends
- invent business assumptions

Use ONLY the supplied information.

If the result contains:

• products
→ discuss product performance

• regions
→ discuss regional performance

• payment methods
→ discuss customer payment preference

• age groups
→ discuss customer demographics

• categories
→ discuss category performance

• profit
→ discuss profitability

• monthly growth
→ discuss growth trend only from the supplied values

If previous conversation or parameters are relevant,
briefly reference them naturally.

--------------------------------------------------

Return Markdown ONLY.

# 📊 Business Insight

## Executive Summary

(2-4 sentences)

## Key Insights

- Insight 1
- Insight 2
- Insight 3

## Recommendation

Give ONE actionable recommendation.

## Suggested Follow-up Questions

Provide exactly 3 questions the user might ask next.

Example:

- Which product generated the highest profit?
- Show sales by payment method.
- Compare sales by category.

--------------------------------------------------

Rules

• Professional tone
• No markdown tables
• No emojis except the heading
• Never mention Python
• Never mention Pandas
• Never mention JSON
• Never mention calculations
• Never mention "provided data"
• Never say "I calculated"
• Keep response under 350 words
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0.2,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an expert Business Intelligence Consultant. "
                    "Provide concise executive summaries and business recommendations."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content